import type { MeetingDetail } from "./types";
import { clockTime, dateLabel } from "./utils";
export function exportMeeting(meeting: MeetingDetail, format: "txt" | "md") {
  const transcript = meeting.segments
    .map((s) => `[${clockTime(s.start_seconds)}] ${s.speaker_name}: ${s.text}`)
    .join("\n\n");
  const content =
    format === "txt"
      ? `${meeting.title}\n${dateLabel(meeting.meeting_date)}\n\n${transcript}`
      : `# ${meeting.title}\n\n${dateLabel(meeting.meeting_date)} · ${Math.round(meeting.duration_seconds / 60)} minutes\n\nParticipants: ${meeting.participants.map((p) => p.name).join(", ")}\n\n## Overview\n\n${meeting.summary_short}\n\n${meeting.summary_detailed.sections.map((s) => `## ${s.title}\n\n${s.bullets.map((b) => `- ${b}`).join("\n")}`).join("\n\n")}\n\n## Key decisions\n\n${meeting.summary_detailed.decisions.map((d) => `- ${d}`).join("\n") || "None detected."}\n\n## Action items\n\n${meeting.action_items.map((a) => `- [${a.completed ? "x" : " "}] ${a.text} — ${a.assignee}${a.due_date ? ` (due ${a.due_date})` : ""}`).join("\n")}\n\n---\nNotes generated by Minutes AI using deterministic demo analysis.\n`;
  const url = URL.createObjectURL(
    new Blob([content], {
      type:
        format === "txt"
          ? "text/plain;charset=utf-8"
          : "text/markdown;charset=utf-8",
    }),
  );
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `${meeting.title.replace(/[^a-z0-9 -]/gi, "").trim() || "minutes-ai-meeting"}.${format}`;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
